version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017'

  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb
