version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: academy_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: academy
    ports:
      - '5432:5432'
    volumes:
      - ./create_db:/docker-entrypoint-initdb.d/


